# Generated by Django 3.0.8 on 2020-07-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimage',
            name='image',
            field=models.ImageField(upload_to='member_images/'),
        ),
    ]
