# Generated by Django 3.0.8 on 2020-07-31 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200731_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='personality',
        ),
        migrations.CreateModel(
            name='MemberPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(choices=[('intelligent', '지적인'), ('calm', '차분한'), ('humorous', '유머있는'), ('optimistic', '낙천적인'), ('introvert', '내향적인'), ('extrovert', '외향적인'), ('emotional', '감성적인'), ('kind', '상냥한'), ('cute', '귀여운'), ('sexy', '섹시한'), ('unique', '4차원인'), ('cheerful', '발랄한'), ('cool', '도도한')], max_length=60)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberIdealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_start', models.PositiveIntegerField(blank=True, null=True)),
                ('age_end', models.PositiveIntegerField(blank=True, null=True)),
                ('tall_start', models.PositiveIntegerField(blank=True)),
                ('tall_end', models.PositiveIntegerField(blank=True)),
                ('region1', models.CharField(blank=True, choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('incheon', '인천'), ('daejeon', '대전'), ('chungbuk', '충북'), ('chungnam', '충남'), ('gangwon', '강원'), ('busan', '부산'), ('gyeongbuk', '경북'), ('gyeongnam', '경남'), ('daegu', '대구'), ('ulsan', '울산'), ('gwangju', '광주'), ('jeonbuk', '전북'), ('jeonnam', '전남'), ('jeju', '제주')], max_length=60)),
                ('region2', models.CharField(blank=True, choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('incheon', '인천'), ('daejeon', '대전'), ('chungbuk', '충북'), ('chungnam', '충남'), ('gangwon', '강원'), ('busan', '부산'), ('gyeongbuk', '경북'), ('gyeongnam', '경남'), ('daegu', '대구'), ('ulsan', '울산'), ('gwangju', '광주'), ('jeonbuk', '전북'), ('jeonnam', '전남'), ('jeju', '제주')], max_length=60)),
                ('body_shape', models.CharField(blank=True, choices=[('normal', '보통체형'), ('plump', '통통한'), ('curvy', '살짝볼륨'), ('glamor', '글래머'), ('thin', '마른'), ('slimfirm', '슬림탄탄')], max_length=60)),
                ('drinking', models.CharField(blank=True, choices=[('sometimes', '가끔 마심'), ('pretty', '어느정도 즐기는편'), ('very', '술자리를 즐김'), ('never', '마시지 않음')], max_length=60)),
                ('smoking', models.CharField(blank=True, choices=[('yes', '흡연'), ('no', '비흡연')], max_length=60)),
                ('religion', models.CharField(blank=True, choices=[('none', '종교 없음'), ('christian', '기독교'), ('catholic', '천주교'), ('buddhism', '불교'), ('wonbuddhism', '원불교'), ('confucian', '유교'), ('islam', '이슬람교')], max_length=60)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
