# Generated by Django 3.0.8 on 2020-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200731_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
