# Generated by Django 3.0.8 on 2020-08-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200802_1624'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='nickname',
            field=models.CharField(default='hjk', max_length=40),
            preserve_default=False,
        ),
    ]
