# Generated by Django 3.0.8 on 2020-08-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200802_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberidealtype',
            name='tall_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberidealtype',
            name='tall_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
